name: linting, building, testing
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs_on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17x ]
  steps:
    - uses: actions/checkout@v2
    - name: Staring Node.js ${{ matrix.node-version }}
      uses: actions.setup-node@1
      with:
        node_version: ${{ matrix.node-version }}
    - name: install module
      run: npm install
    - name: build project
      run: npm run build:prod
    - name: lint typescript
      run: npm run lint:ts
    - name: lint css
      run: npm run lint:scss
    - name: unit testing
      run: npm run test:unit